CREATE DATABASE c3;
USE c3;
CREATE TABLE st(
s_id INT PRIMARY KEY,
 gender ENUM('M','F'),
e_mail VARCHAR(20),
contact INT(20),
city CHAR(20)
);


ALTER TABLE st ADD COLUMN s_name VARCHAR(25);
TRUNCATE TABLE st;
ALTER TABLE st ADD COLUMN percentage FLOAT(2,2);
ALTER TABLE st MODIFY COLUMN contact FLOAT(2,2);
ALTER TABLE st MODIFY COLUMN contact INT(20);
ALTER TABLE st MODIFY COLUMN percentage FLOAT(2,2);
ALTER TABLE st DROP COLUMN percentage;
ALTER TABLE st DROP COLUMN city;
ALTER TABLE st ADD COLUMN marks INT;
SELECT * FROM st;
